# Generated by Django 4.0.4 on 2023-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storeimage_image_urls_storemenu'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.ManyToManyField(related_name='user_order', through='orders.Order', to='stores.store'),
        ),
    ]
