# Generated by Django 4.0.4 on 2023-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storeimage_image_urls_storemenu'),
        ('users', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(related_name='user_like', through='users.Like', to='stores.store'),
        ),
    ]
