# Generated by Django 4.0.4 on 2023-05-15 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image_urls',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_urls', models.CharField(default=None, max_length=500)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='stores.store')),
            ],
            options={
                'db_table': 'store_menu',
            },
        ),
    ]
